package com.example.springbootaws.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Product")
public class Product 
{
   private String id;
   private String name;
   private String description;
   private int price;
   
   public Product(String name, String description, int price)
   {
	   this.name = name;
	   this.description  = description;
	   this.price = price;
   }
   
   @DynamoDBHashKey
   @DynamoDBAutoGeneratedKey 
   public String getId() {
	return id;
   }
   public void setId(String id) {
	this.id = id;
   }
   @DynamoDBAttribute
   public String getName() {
	return name;
   }
   public void setName(String name) {
	this.name = name;
   }
   @DynamoDBAttribute
   public String getDescription() {
	return description;
   }
   public void setDescription(String description) {
	this.description = description;
   }
   @DynamoDBAttribute
   public int getPrice() {
	return price;
  }
   public void setPrice(int price) {
	this.price = price;
   }
   
   
}
